server:
  port: 8201 #指定运行端口
spring:
  application:
    name: user-service #指定服务名称
  zipkin: #链路追踪配置
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 0.1 #设置Sleuth的抽样收集概率
eureka:
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（客户端需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（客户端需要开启）
    service-url:
      defaultZone: http://localhost:8001/eureka/ #配置注册中心地址
  server:
    enable-self-preservation: false #关闭保护模式