server:
  port: 8002 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
eureka:
  instance:
    hostname: replica1 #指定主机地址
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心开启,从另一个eureka服务器获取服务列表）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心开启，注册到另一个eureka服务器，互相注册形成eureka服务器集群）
    service-url:
      defaultZone: http://localhost:8003/eureka/ #注册到另一个注册中心
  server:
    enable-self-preservation: false #关闭保护模式